name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Iowa
main: HCF
softdepend: [Essentials, ProtocolLib, WorldEdit]
depend: [Core, ProtocolSupport]
license: MIT
